### ISSUE TITLE
[Bug] Rotating cameras does not work with omxplayer

### ISSUE THREAD

**Issue by davidasnider** [shbatm/MMM-RTSPStream#68]
**Describe the bug**
When using the omxplayer with multiple cameras and rotating amongst them in one window, omxplayer never switches from the first camera in the list.  When using VLC, rotation works great... however, there is a brief period where vlc resizes the window which can be distracting. Omxplayer does NOT resize.

**To Reproduce**
1. Configure multiple cameras
1. Configure use of omxplayer
1. Restart mirror, observe no rotation of image

**Expected behavior**
Omxplayer should rotate through images just like vlc

**Configuration**
Please include:

```
		{
			module: "MMM-RTSPStream",
			position: "bottom_right",
			config: {
				autoStart: true,
				rotateStreams: true,
				rotateStreamTimeout: 10,
				moduleWidth: 568,
				moduleHeight: 320,
				localPlayer: 'omxplayer',
				remotePlayer: 'none',
				showSnapWhenPaused: true,
				remoteSnaps: true,
				shutdownDelay: 12,
				omxRestart: 24,
				moduleOffset: { left: 0, top: -35 },
				stream1: {
					name: 'Driveway',
					url: 'rtsp://obfuscated/cam/realmonitor?channel=1&subtype=1',
					frameRate: 'undefined',
					hdUrl: 'rtsp://obfuscated/cam/realmonitor?channel=1&subtype=0',
					snapshotType: 'url',
					snapshotRefresh: 10,
					width: 568,
					height: 320,
					muted: true,
				},
				stream2: {
					name: 'HotTub',
					url: 'rtsp://obfuscated/cam/realmonitor?channel=2&subtype=1',
					frameRate: 'undefined',
					hdUrl: 'rtsp://obfuscated/cam/realmonitor?channel=2&subtype=0',
					snapshotType: 'url',
					snapshotRefresh: 10,
					width: 568,
					height: 320,
					muted: true,
				},
				stream3: {
					name: 'Sideyard',
					url: 'rtsp://obfuscated/cam/realmonitor?channel=3&subtype=1',
					frameRate: 'undefined',
					hdUrl: 'rtsp://obfuscated/cam/realmonitor?channel=3&subtype=0',
					snapshotType: 'url',
					snapshotRefresh: 10,
					width: 568,
					height: 320,
					muted: true,
				},
				stream4: {
					name: 'Backyard',
					url: 'rtsp://obfuscated/cam/realmonitor?channel=4&subtype=1',
					frameRate: 'undefined',
					hdUrl: 'rtsp://obfuscated/cam/realmonitor?channel=4&subtype=0',
					snapshotType: 'url',
					snapshotRefresh: 10,
					width: 568,
					height: 320,
					muted: true,
				},
				stream5: {
					name: 'LivingRoom',
					url: 'rtsp://obfuscated/cam/realmonitor?channel=5&subtype=1',
					frameRate: 'undefined',
					hdUrl: 'rtsp://obfuscated/cam/realmonitor?channel=5&subtype=0',
					snapshotType: 'url',
					snapshotRefresh: 10,
					width: 568,
					height: 320,
					muted: true,
				},

```

* It may be easier to post these in a [Gist](https://gist.github.com) and post the link here.

**Logs**
If applicable, please include the relevant logs to help explain your problem.
    + From the console or `~/.pm2/logs/`
    + From the web console using DevTools (<key>Ctrl</key>+<key>Shift</key>+<key>I</key>)

**Comment by davidasnider** [comment]
I did see this in the error log.. I'll investigate `omx_stream1`

```
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/magicmirror/.npm/_logs/2020-06-24T16_16_35_207Z-debug.log
[2020-06-24 16:17:12.812] [ERROR]  TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at stopProcs (/home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_helper.js:469:32)
    at /home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_helper.js:498:17
    at /home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2/lib/API.js:606:19
    at /home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:200:13)
    at Parser._write (/home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
[2020-06-24 16:17:21.860] [ERROR]  TypeError: Cannot set property 'omx_stream1' of undefined
    at /home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_helper.js:369:83
    at /home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2/lib/API.js:1056:23
    at /home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2/lib/API.js:1134:21
    at /home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/async/internal/once.js:12:16
    at iterateeCallback (/home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/async/internal/eachOfLimit.js:48:24)
    at /home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/async/internal/onlyOnce.js:12:16
    at /home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2/lib/API.js:1129:11
    at /home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/home/magicmirror/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:200:13)
```
