### ISSUE TITLE
ELIFECYCLE errno 7 after new install

### ISSUE THREAD

**Issue by ksdehoff** [shbatm/MMM-RTSPStream#70]
**Describe the bug**
I'm a new MM2 user.  I have a brand new raspberry pi os install on a pi 4.  After a new install of MMM-RTSPStream (both main and develop have been tried) MM fails to start.  

console error message:

events.js:177
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:413:19)
    at writeOrBuffer (_stream_writable.js:401:5)
    at WriteStream.Writable.write (_stream_writable.js:301:11)
    at Object.con.<computed> [as error] (/home/pi/MagicMirror/node_modules/console-stamp/main.js:148:46)
    at process.<anonymous> (/home/pi/MagicMirror/js/app.js:37:6)
    at process.emit (events.js:205:15)
    at process._fatalException (internal/process/execution.js:146:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 7

debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start', 'dev' ]
2 info using npm@6.14.6
3 info using node@v10.22.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.12.0~prestart: magicmirror@2.12.0
6 info lifecycle magicmirror@2.12.0~start: magicmirror@2.12.0
7 verbose lifecycle magicmirror@2.12.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle magicmirror@2.12.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle magicmirror@2.12.0~start: CWD: /home/pi/MagicMirror
10 silly lifecycle magicmirror@2.12.0~start: Args: [ '-c',
10 silly lifecycle   'DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"' ]
11 silly lifecycle magicmirror@2.12.0~start: Returned: code: 7  signal: null
12 info lifecycle magicmirror@2.12.0~start: Failed to exec start script
13 verbose stack Error: magicmirror@2.12.0 start: `DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"`
13 verbose stack Exit status 7
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid magicmirror@2.12.0
15 verbose cwd /home/pi/MagicMirror/config
16 verbose Linux 5.4.51-v7l+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "dev"
18 verbose node v10.22.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 7
22 error magicmirror@2.12.0 start: `DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"`
22 error Exit status 7
23 error Failed at the magicmirror@2.12.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 7, true ]

**To Reproduce**

config.js segment
		    {
		        module: 'MMM-RTSPStream',
		        position: 'middle_center',
		        config: {
		            initialSetup: true
		        }
		    },

**Expected behavior**
mm shouldn't crash

**Comment by ksdehoff** [comment]
Update:
This problem occurs when I connect remotely via vnc/xrdp.  When running on the console no errors occur.  How can I fix this?
