### ISSUE TITLE
/MMM-RTSPStream/config.html can't be reached - MM won't startup

### ISSUE THREAD

**Issue by Coolie1101** [shbatm/MMM-RTSPStream#91]
**To Reproduce**
1. Run script from: - https://github.com/shbatm/MMM-RTSPStream#quick-install
2. Added Config: - https://github.com/shbatm/MMM-RTSPStream#using-the-module
3. Open a web-browser and navigated to: - http://192.168.200.210:8080/MMM-RTSPStream/config.html
4. Got error: - Cannot GET /MMM-RTSPStream/config.html

**Expected behavior**
As per the docs, expected to reach the tool to be able to generate the config file details.

**Configuration**
```
    		{
        		module: 'MMM-RTSPStream',
        		position: 'bottom_left',
        		config: {
            		initialSetup: true,
        		}
    		},
```
**Logs**
    + From `~/.pm2/logs/`
```
0|mm  | [26.10.2021 08:23.01.634] [LOG]
0|mm  | Starting MagicMirror: v2.17.1
0|mm  | [26.10.2021 08:23.01.652] [LOG]
0|mm  | Loading config ...
0|mm  | [26.10.2021 08:23.01.670] [LOG]
0|mm  | Loading module helpers ...
0|mm  | [26.10.2021 08:23.01.680] [LOG]
0|mm  | No helper found for module: MMM-Snow.
0|mm  | [26.10.2021 08:23.01.687] [LOG]
0|mm  | No helper found for module: alert.
0|mm  | [26.10.2021 08:23.01.726] [LOG]
0|mm  | Initializing new module helper ...
0|mm  | [26.10.2021 08:23.01.735] [LOG]
0|mm  | Module helper loaded: updatenotification
0|mm  | [26.10.2021 08:23.01.738] [LOG]   No helper found for module: clock.
0|mm  | [26.10.2021 08:23.02.047] [LOG]
0|mm  | Initializing new module helper ...
0|mm  | [26.10.2021 08:23.02.049] [LOG]   Module helper loaded: calendar
0|mm  | [26.10.2021 08:23.02.133] [ERROR]
0|mm  | WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
0|mm  | Require stack:
0|mm  | - /home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js
0|mm  | - /home/pi/MagicMirror/js/app.js
0|mm  | - /home/pi/MagicMirror/js/electron.js
0|mm  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|mm  | -
0|mm  | [26.10.2021 08:23.02.135] [LOG]   Loading module helpers ...
0|mm  | [26.10.2021 08:23.02.137] [LOG]   No helper found for module: MMM-Snow.
0|mm  | [26.10.2021 08:23.02.139] [LOG]   No helper found for module: alert.
0|mm  | [26.10.2021 08:23.02.142] [LOG]   Initializing new module helper ...
0|mm  | [26.10.2021 08:23.02.144] [LOG]   Module helper loaded: updatenotification
0|mm  | [26.10.2021 08:23.02.147] [LOG]
0|mm  | No helper found for module: clock.
0|mm  | [26.10.2021 08:23.02.149] [LOG]   Initializing new module helper ...
0|mm  | [26.10.2021 08:23.02.150] [LOG]   Module helper loaded: calendar
0|mm  | [26.10.2021 08:23.02.157] [ERROR]
0|mm  | App threw an error during load
0|mm  | [26.10.2021 08:23.02.162] [ERROR] Error: Cannot find module 'request'
0|mm  | Require stack:
0|mm  | - /home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js
0|mm  | - /home/pi/MagicMirror/js/app.js
0|mm  | - /home/pi/MagicMirror/js/electron.js
0|mm  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|mm  | -
0|mm  |     at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
0|mm  |     at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
0|mm  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|mm  |     at Module._load (internal/modules/cjs/loader.js:732:27)
0|mm  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|mm  |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js:11:15)
0|mm  |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
0|mm  | [26.10.2021 08:23.02.165] [ERROR] Whoops! There was an uncaught exception...
0|mm  | [26.10.2021 08:23.02.179] [ERROR]
0|mm  | Error: Cannot find module 'request'
0|mm  | Require stack:
0|mm  | - /home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js
0|mm  | - /home/pi/MagicMirror/js/app.js
0|mm  | - /home/pi/MagicMirror/js/electron.js
0|mm  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|mm  | -
0|mm  |     at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
0|mm  |     at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
0|mm  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|mm  |     at Module._load (internal/modules/cjs/loader.js:732:27)
0|mm  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|mm  |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js:11:15)
0|mm  |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
0|mm  |   code: 'MODULE_NOT_FOUND',
0|mm  |   requireStack: [
0|mm  |     '/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js',
0|mm  |     '/home/pi/MagicMirror/js/app.js',
0|mm  |     '/home/pi/MagicMirror/js/electron.js',
0|mm  |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|mm  |     undefined
0|mm  |   ]
0|mm  | }
0|mm  | [26.10.2021 08:23.02.181] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | [26.10.2021 08:23.02.182] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

    + From the web console
`(index):7288 crbug/1173575, non-JS module files deprecated.`

**Comment by mrBlackHat777** [comment]
open `nano package.json` and add `"request": "^2.88.2"` to your dependencies . Then `npm install `
